### ISSUE TITLE
Can not launch on Mac

### ISSUE THREAD

**Issue by Ariaszzzhc** [Kasax007/Modpack-Development#25]
**Describe the bug**
can not launch on Mac, even if delete voice chat mod

**To Reproduce**
just use MultiMC start game

**Screenshots + Crash log**

<img width="1188" alt="WX20220222-152905@2x" src="https://user-images.githubusercontent.com/17329403/155083405-551bbb9e-0684-45a3-962b-69453c37b993.png">

Crash Log:
[15:24:20] [Render thread/FATAL]: Unreported exception thrown!
java.lang.LinkageError: loader constraint violation: when resolving method 'void ca.weblite.objc.NSObject.<init>(com.sun.jna.Pointer)' the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @41ee392b of the current class, net/minecraft/class_6417, and the class loader 'app' for the method's defining class, ca/weblite/objc/NSObject, have different Class objects for the type com/sun/jna/Pointer used in the signature (net.minecraft.class_6417 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @41ee392b, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @2ea6137; ca.weblite.objc.NSObject is in unnamed module of loader 'app')
	at net.minecraft.class_6417.method_37463(class_6417.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_6417.method_37461(class_6417.java:15) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_4479(class_1041.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_4485(class_1041.java:387) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:313) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1142) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2/22/22, 3:24 PM
Description: Unexpected error

java.lang.LinkageError: loader constraint violation: when resolving method 'void ca.weblite.objc.NSObject.<init>(com.sun.jna.Pointer)' the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @41ee392b of the current class, net/minecraft/class_6417, and the class loader 'app' for the method's defining class, ca/weblite/objc/NSObject, have different Class objects for the type com/sun/jna/Pointer used in the signature (net.minecraft.class_6417 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @41ee392b, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @2ea6137; ca.weblite.objc.NSObject is in unnamed module of loader 'app')
	at net.minecraft.class_6417.method_37463(class_6417.java:21)
	at net.minecraft.class_6417.method_37461(class_6417.java:15)
	at net.minecraft.class_1041.method_4479(class_1041.java:349)
	at net.minecraft.class_1041.method_4485(class_1041.java:387)
	at net.minecraft.class_1041.method_15998(class_1041.java:313)
	at net.minecraft.class_310.method_1523(class_310.java:1142)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

detailed log here: 
[latest.log](https://github.com/Kasax007/Modpack-Development/files/8114456/latest.log)

**Version of the modpack**
v10

**Additional context**
deleted voice chat mod

**Comment by Kasax007** [comment]
From what I found out this seems to be a vanilla-related Minecraft bug. https://bugs.mojang.com/browse/MC-117789 
What I can suggest for you to try, is to download the curse forge launcher and play the mod pack from there. I have had people having issues with MultiMC before, so it could also be related to that. When going through the crash log I sadly can't identify a mod, which causes this. Make sure your java is also in version 17 tho. Other than that I don't exactly know what could cause this. Please let me know if you can launch the game over the curse forge launcher. 
Also, even tho you said you removed the voice chat mod your crash log still looks similar like this voice chat issue, which is weird: https://github.com/henkelmax/simple-voice-chat/issues/251

**Comment by Kasax007** [comment]
Since no further update was given this issue is regarded as solved.
