### ISSUE TITLE
Disconnect From Server On Start

### ISSUE THREAD

**Issue by Afoekon** [Kasax007/Modpack-Development#8]
I am not sure exactly what is going on as I'm not getting any error, but every time I try to connect to my server I keep getting disconnected. I checked the server console and it just says I disconnected. I've been messing around with mod packs all day and haven't had any issuing connecting to my server until this mod pack.

**Comment by Kasax007** [comment]
What version of the modpack and server are you using? If you somehow got the V3 version, yeah that one is broken and shouldn't be up for download. But the V4 version so far has worked considering the feedback.

**Comment by Afoekon** [comment]
It was V4, but the people I paid to set up your modpack on my server at Bisect Hosting set it up incorrectly. They set the sever up as forge not a fabric. I corrected it, but I kept getting an error, see below, right after the server loaded. Turns out that the mod file voicechat-fabric-1.18.1-2.1.28.jar that was included in the pack was causing the server to shutdown. I deleted it this morning and It works great now.

[28.12 21:30:43] [Server] [VoiceChatServerThread/ERROR]: Failed to bind to address '0.0.0.0', make sure no other application is running at UDP port 24454
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: java.net.BindException: Address already in use
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at java.base/sun.nio.ch.Net.bind0(Native Method)
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at java.base/sun.nio.ch.Net.bind(Net.java:555)
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1194)
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1164)
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:107)
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at java.base/java.net.DatagramSocket.createDelegate(DatagramSocket.java:1426)
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:330)
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:389)
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at de.maxhenkel.voicechat.plugins.impl.VoicechatSocketImpl.open(VoicechatSocketImpl.java:32)
[28.12 21:30:43] [Server] [VoiceChatServerThread/INFO]: [STDERR]: at de.maxhenkel.voicechat.voice.server.Server.run(Server.java:60)
[28.12 21:30:44] [Server] 2021-12-21:30:44,014 Server thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
[28.12 21:30:56] [Server] [Server thread/INFO]: [Textile Backup] Backup started by: Server Shutdown on: 2021.12.28_21-30-56
[28.12 21:30:56] [Server] [Server thread/INFO]: [Textile Backup] Starting backup
[28.12 21:30:57] [Server] [Server thread/INFO]: [Textile Backup] Compression took: 00.278 seconds.
[28.12 21:30:58] [Multicraft] Server shut down (running)
